### ISSUE TITLE
UK / GB not returning city 

### ISSUE THREAD

**Issue by gareth326771** [stimulus-components/stimulus-places-autocomplete#11]
All working fine for other countries but the data from the UK is not returning the city, sometimes the city does appear in the county, but other times the county will appear there!

Any help appreciated. @guillaumebriday

**Comment by gareth326771** [comment]
Found the issue...

For UK addresses city is often returned as `postal_town` not `locality` from the Google API.

Implementing fix on my project but unsure how to use typescript etc to update this repo.

**Comment by guillaumebriday** [comment]
If it's still an issue please reopen it in the main repo: https://github.com/stimulus-components/stimulus-components
