### ISSUE TITLE
Add more Address attributes 

### ISSUE THREAD

**Issue by janpeterka** [stimulus-components/stimulus-places-autocomplete#12]
Hi, searching for replacement for now deprecated [geocomplete](https://github.com/ubilabs/geocomplete), I was happy to find this, as we are all into Stimulus!

I tried playing with this a bit, and there's one small issue - this controller doesn't support all fields we use.

Would it be possible to add these standard fields, returned from Google API, into targets and Address:
- `formatted_address`
- `street_address`
- `locality`
- `sublocality`
- `neighborhood`
- `political`

?

I can prepare PR, if this is acceptable.

Thank you!

(If it's not added, we will have to create our own controller, as we don'ŧ use ts in our project, so just extending this would be painful, if not impossible)

**Comment by guillaumebriday** [comment]
Yeah Stimulus all the things 🥳 

Sure you can open a PR that would be nice! 

Thanks in advance
