### ISSUE TITLE
Add Latitude and longitude address components

### ISSUE THREAD

**Issue by pcarballeda** [stimulus-components/stimulus-places-autocomplete#2]
Hello. I am wondering if could be possible to add new latitude and longitude targets to the component just like the other address components. 

Personally I would find it really useful, not sure if this is in your plans.

````
<input type="text" data-common--autocomplete-target="city" />
<input type="text" data-common--autocomplete-target="streetNumber" />
<input type="text" data-common--autocomplete-target="route" />
<input type="text" data-common--autocomplete-target="county" />
<input type="text" data-common--autocomplete-target="state" />
<input type="text" data-common--autocomplete-target="postalCode" />
<input type="text" data-common--autocomplete-target="country" />

<input type="text" data-common--autocomplete-target="latitude" />
<input type="text" data-common--autocomplete-target="longitude" />
````

Thank you for this awesome work!

**Comment by guillaumebriday** [comment]
Done [here](https://github.com/stimulus-components/stimulus-places-autocomplete/commit/3ca985210e25739427f15342459a153d9ad615d3) 👍

**Comment by pcarballeda** [comment]
> Will release it later today

Thank you so much!

**Comment by guillaumebriday** [comment]
https://github.com/stimulus-components/stimulus-places-autocomplete/releases/tag/v0.3.0
