### ISSUE TITLE
Adding types value

### ISSUE THREAD

**Issue by marckohlbrugge** [stimulus-components/stimulus-places-autocomplete#5]
Would you consider making the `types` option configurable through a `data-places-types-value` ?

See https://developers.google.com/maps/documentation/places/web-service/autocomplete#place_types

**Comment by guillaumebriday** [comment]
Why not. I never used this option so maybe you could open a PR with what you need?

**Comment by yann120** [comment]
A workaround for this is to extend the stimulus controller
Here is the controller that I extended for having only cities as types : 
``` js
import PlacesAutocomplete from 'stimulus-places-autocomplete'

export default class extends PlacesAutocomplete {
  connect() {
    super.connect()
    this.autocomplete
  }

  // You can set the Autocomplete options in this getter.
  get autocompleteOptions() {
    return {
      types: ['(cities)']
    }
  }
}
```

Don't forget to import the controller then 😉 (I always forgot haha)

**Comment by guillaumebriday** [comment]
> A workaround for this is to extend the stimulus controller Here is the controller that I extended for having only cities as types :
> 
> ```js
> import PlacesAutocomplete from 'stimulus-places-autocomplete'
> 
> export default class extends PlacesAutocomplete {
>   connect() {
>     super.connect()
>     this.autocomplete
>   }
> 
>   // You can set the Autocomplete options in this getter.
>   get autocompleteOptions() {
>     return {
>       types: ['(cities)']
>     }
>   }
> }
> ```
> 
> Don't forget to import the controller then 😉 (I always forgot haha)

Yep, that's the way to go!

Thanks 🙏
