### ISSUE TITLE
Could not resolve "stimulus"

### ISSUE THREAD

**Issue by morgler** [stimulus-components/stimulus-places-autocomplete#6]
The latest Rails stimulus packages are at "@hotwired/stimulus" instead of "stimulus".  This is why this code creates an error when trying to include stimulus-places-autocomplete.

**Comment by guillaumebriday** [comment]
Fixed by https://github.com/stimulus-components/stimulus-places-autocomplete/releases/tag/v0.5.0
Thanks @morgler
